create schema auth;


create table auth.users (
id varchar(100),
username varchar(100),
password varchar(100),
email varchar(100),
is_active boolean,
token uuid
);

create sequence auth.users_id_seq;

alter table auth.users alter column id set default nextval('auth.users_id_seq');


 CREATE TABLE AUTH.SESSION (
   PRIMARY_ID CHAR(36) NOT NULL,
   SESSION_ID CHAR(36) NOT NULL,
   CREATION_TIME BIGINT NOT NULL,
   LAST_ACCESS_TIME BIGINT NOT NULL,
   MAX_INACTIVE_INTERVAL INT NOT NULL,
   EXPIRY_TIME BIGINT NOT NULL,
   PRINCIPAL_NAME VARCHAR(100),
   CONSTRAINT SPRING_SESSION_PK PRIMARY KEY (PRIMARY_ID)
 );

 CREATE UNIQUE INDEX AUTH_SESSION_IX1 ON AUTH.SESSION (SESSION_ID);
 CREATE INDEX AUTH_SESSION_IX2 ON AUTH.SESSION (EXPIRY_TIME);
 CREATE INDEX AUTH_SESSION_IX3 ON AUTH.SESSION (PRINCIPAL_NAME);

 CREATE TABLE AUTH.SESSION_ATTRIBUTES (
  SESSION_PRIMARY_ID CHAR(36) NOT NULL,
  ATTRIBUTE_NAME VARCHAR(200) NOT NULL,
  ATTRIBUTE_BYTES BYTEA NOT NULL,
  CONSTRAINT AUTH_SESSION_ATTRIBUTES_PK PRIMARY KEY (SESSION_PRIMARY_ID, ATTRIBUTE_NAME),
  CONSTRAINT AUTH_SESSION_ATTRIBUTES_FK FOREIGN KEY (SESSION_PRIMARY_ID) REFERENCES AUTH.SESSION(PRIMARY_ID) ON DELETE CASCADE
 );

 CREATE INDEX AUTH_SESSION_ATTRIBUTES_IX1 ON AUTH.SESSION_ATTRIBUTES (SESSION_PRIMARY_ID);


create sequence auth.roles_id_seq;
CREATE TABLE auth.roles (
    id varchar(50) PRIMARY KEY,
    name VARCHAR(50) NOT NULL UNIQUE -- Example: 'ROLE_ADMIN', 'ROLE_USER'
);

ALTER TABLE auth.users ALTER COLUMN id SET DEFAULT nextval('auth.users_id_seq');

ALTER TABLE auth.roles ALTER COLUMN id SET DEFAULT nextval('auth.roles_id_seq');

ALTER TABLE auth.users ADD CONSTRAINT unique_usr_id UNIQUE (id);

alter table auth.roles add constraint unique_role_id unique (id);

CREATE TABLE auth.user_roles (
    user_id varchar(50) NOT NULL,
    role_id varchar(50) NOT NULL,
    PRIMARY KEY (user_id, role_id),
    FOREIGN KEY (user_id) REFERENCES auth.users(id),
    FOREIGN KEY (role_id) REFERENCES auth.roles(id)
);

