spring.application.name=authgate

server.port=8081

# НАСТРОЙКИ ДЛЯ ПОДКЛЮЧЕНИЯ К БД
# Connection URL (format: jdbc:postgresql://<host>:<port>/<database_name>)
spring.datasource.url=jdbc:postgresql://localhost:5432/postgres

# Database credentials
spring.datasource.username=postgres
spring.datasource.password=postgres

# PostgreSQL Driver (Optional: Spring Boot usually detects this automatically)
spring.datasource.driver-class-name=org.postgresql.Driver

# ПОЧТОВЫЙ СЕРВЕР
#spring.mail.host=smtp.yandex.ru
#spring.mail.port=587
#spring.mail.username=mega1penguin@yandex.ru
#spring.mail.password=glyaqxsdgisnhfpz
#spring.mail.properties.mail.smtp.auth=true
#spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=jook200200@gmail.com
#Это не пароль от гугл аккаунта, а пароль приложения, сгенерированный в гугле
spring.mail.password=pzgihnaslsvcekgp
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
